### ISSUE TITLE
Add a Nim benchmark

### ISSUE THREAD

**Issue by Calinou** [cart/godot3-bunnymark#1]
It would be interesting to see how the [godot-nim](https://github.com/pragmagic/godot-nim) binding performs, especially compared to C++ and Mono.

If you're interested in this, I can attempt porting the benchmark to Nim.

**Comment by cart** [comment]
I am definitely interested!  If you port it I'll add it to the next run.

**Comment by cart** [comment]
@Capital-EX handled this in #5
