### ISSUE TITLE
Readme: Running section

### ISSUE THREAD

**Issue by thoughton** [cart/godot3-bunnymark#14]
Apologies if I'm just missing something obvious, but in the "Running" steps in the Readme is it possibly missing a step regarding when and _how_ to build Godot itself?

**Comment by cart** [comment]
Sorry for the delay! First, you can use official builds if you don't need ECMAScript.
For more info on that:
* [Building Godot](https://docs.godotengine.org/en/3.1/development/compiling/index.html)
* [Building Godot with the ECMAScript module](https://github.com/Geequlim/ECMAScript)
