### ISSUE TITLE
Update benchmark result in README.MD

### ISSUE THREAD

**Issue by RUSshy** [cart/godot3-bunnymark#22]
Bindings have improved since the last 2 years, i think it should be re-run to show REAL numbers

Thanks

**Comment by cart** [comment]
I no longer have the time or motivation to maintain this project. I'm now working full time on my game engine [Bevy](https://bevyengine.org/).

If anyone wants to handle updates, they're welcome to fork. I'll mark this as "archived" and update the readme to make it clear that the numbers are old and the project unmaintained.
