### ISSUE TITLE
Possible V3 bunnymark: Scene Instancing

### ISSUE THREAD

**Issue by Capital-EX** [cart/godot3-bunnymark#7]
Dynamic scene creation is an import tool in Godot.  It would be interesting to see how each language handles it.

**Comment by cart** [comment]
Sounds like a great idea.  How would the benchmark work?  Would it make .instance() calls then position the resulting nodes?

**Comment by Capital-EX** [comment]
Parent scene creates an instance of a bunny scene and sets it's initial position.  The Bunny scene then controls its own motion.

**Comment by cart** [comment]
See #22
