### ISSUE TITLE
Scons build line

### ISSUE THREAD

**Issue by hpvb** [cart/godot3-bunnymark#8]
Hi! Thanks for your work on this. It could be useful to some people. I just have one question/comment in the README you say that the scons command you used was.

```scons p=x11 target=release_debug tools=yes builtin_openssl=yes module_mono_enabled=yes -j4 -use_lto=yes```

I believe that if you indeed did '-use_lto' and not 'use_lto' that no LTO was actually implemented. In my synthetic benchmarks after my latest rounds of improvements (already some months ago now however) performance increased quite a lot after a successful LTO build.

**Comment by cart** [comment]
Fortunately, I never actually ran the command above.  I use Visual Studio Code's task system to build Godot:

```json
{
    "taskName": "benchmark",
    "command": "scons",
    "args": [
        "p=x11",
        "target=release_debug",
        "tools=yes",
        "builtin_openssl=yes",
        "module_mono_enabled=yes",
        "use_lto=yes",
        "-j4"
    ],
    "group": "build",
    "problemMatcher": []
}
```

Which would result in the desired:
```scons p=x11 target=release_debug tools=yes builtin_openssl=yes module_mono_enabled=yes use_lto=yes -j4```

The "-" error above was a typo that resulted from me manually converting the task to a command.  Regardless, I actually think it doesn't matter.  Scons will fail if there is an unidentified parameter:
* ```-use_lto=yes``` results in the build starting
* ```-use_lto_im_not_real=yes``` results in the build failing

This leads me to believe that ```-use_lto``` would work.

**Comment by hpvb** [comment]
Alright! Thanks for your explanation!
